---
name: master-depls
releases:
  app-autoscaler:
    repository: cloudfoundry-incubator/app-autoscaler-release
    version: 1.2.2
  backup-and-restore-sdk:
    repository: cloudfoundry-incubator/backup-and-restore-sdk-release
    version: 1.18.28
  binary-buildpack:
    repository: cloudfoundry/binary-buildpack-release
    version: 1.0.36
  bosh:
    repository: cloudfoundry/bosh
    version: 273.0.0
  bosh-dns:
    repository: cloudfoundry/bosh-dns-release
    version: 1.29.0
  bosh-dns-aliases:
    repository: cloudfoundry/bosh-dns-aliases-release
    version: 0.0.4
  bosh-openstack-cpi:
    repository: cloudfoundry/bosh-openstack-cpi-release
    version: '46'
  bosh-vsphere-cpi:
    repository: cloudfoundry/bosh-vsphere-cpi-release
    version: '72'
  bpm:
    repository: cloudfoundry/bpm-release
    version: 1.1.15
  capi:
    repository: cloudfoundry/capi-release
    version: 1.126.0
  cf-cli:
    repository: bosh-packages/cf-cli-release
    version: 1.38.0
  cf-mysql:
    repository: orange-cloudfoundry/cf-mysql-release
    skip_branch_checkout: false
    tag_prefix: ''
    version: 38.1.0
  cf-networking:
    repository: cloudfoundry/cf-networking-release
    version: 3.0.0
  cf-smoke-tests:
    repository: cloudfoundry/cf-smoke-tests-release
    version: 41.0.2
  cf-syslog-drain:
    repository: cloudfoundry/cf-syslog-drain-release
    version: 10.2.11
  cflinuxfs3:
    repository: cloudfoundry/cflinuxfs3-release
    version: 0.274.0
  credhub:
    repository: pivotal-cf/credhub-release
    skip_branch_checkout: false
    tag_prefix: ''
    version: 2.11.2
  cron:
    repository: cloudfoundry-community/cron-boshrelease
    version: 1.3.1
  diego:
    repository: cloudfoundry/diego-release
    version: 2.59.0
  docker:
    repository: cloudfoundry-incubator/docker-boshrelease
    version: 35.3.4
  dotnet-core-buildpack:
    repository: cloudfoundry/dotnet-core-buildpack-release
    version: 2.3.23
  garden-runc:
    repository: cloudfoundry/garden-runc-release
    version: 1.20.0
  generic-scripting:
    repository: orange-cloudfoundry/generic-scripting-release
    version: '3'
  generic-taint-jobs:
    repository: orange-cloudfoundry/generic-taint-jobs-release
    version: '2'
  go-buildpack:
    repository: cloudfoundry/go-buildpack-release
    version: 1.9.26
  haproxy:
    repository: cloudfoundry-community/haproxy-boshrelease
    version: 11.10.2
  helm-kubectl:
    repository: orange-cloudfoundry/helm-kubectl-boshrelease
    tag_prefix: ''
    version: '39'
  java-buildpack:
    repository: cloudfoundry/java-buildpack-release
    version: '4.46'
  jumpbox:
    comments: |
      This release is a used at least by master-depls/metabase/deployment-dependencies-70-enable-bi-cdc-event-infra.yml.
      We should check in future version (in v54, at least) if we can remove it.
      Currently in v53, this profile seems not enabled.
    repository: cloudfoundry-community/jumpbox-boshrelease
    version: 4.8.14
  k3s:
    repository: orange-cloudfoundry/k3s-boshrelease
    version: '29'
  log-cache:
    repository: cloudfoundry/log-cache-release
    version: 2.11.5
  loggregator:
    repository: cloudfoundry/loggregator-release
    version: 106.6.2
  loggregator-agent:
    repository: cloudfoundry/loggregator-agent-release
    version: 6.3.8
  logsearch:
    repository: cloudfoundry-community/logsearch-boshrelease
    version: 211.1.0
  logsearch-for-cloudfoundry:
    repository: cloudfoundry-community/logsearch-for-cloudfoundry
    version: 211.1.0
  metabase:
    repository: orange-cloudfoundry/metabase-boshrelease
    version: '5'
  metrics-discovery:
    repository: cloudfoundry/metrics-discovery-release
    version: 3.0.8
  minio:
    repository: minio/minio-boshrelease
    version: 2021-10-23T03-28-24Z
  nats:
    repository: cloudfoundry/nats-release
    version: '43'
  networking:
    repository: orange-cloudfoundry/networking-release
    skip_branch_checkout: false
    version: '10'
  nginx-buildpack:
    repository: cloudfoundry/nginx-buildpack-release
    version: 1.1.21
  nginx:
    repository: cloudfoundry-community/nginx-release
    tag_prefix: ''
    version: 1.19.1
  node-exporter:
    repository: cloudfoundry-community/node-exporter-boshrelease
    version: 5.0.0
  nodejs-buildpack:
    repository: cloudfoundry/nodejs-buildpack-release
    version: 1.7.44
  oauth2-proxy:
    repository: cloudfoundry-community/oauth2-proxy-boshrelease
    version: 0.3.0
  open-iscsi:
    repository: orange-cloudfoundry/open-iscsi-boshrelease
    tag_prefix: ''
    version: '1'
  orange-prometheus-addons:
    repository: orange-cloudfoundry/orange-prometheus-addons-boshrelease/
    version: '3'
  os-conf:
    repository: cloudfoundry/os-conf-release
    version: 22.1.1
  php-buildpack:
    repository: cloudfoundry/php-buildpack-release
    version: 4.4.32
  postgres:
    repository: cloudfoundry/postgres-release
    version: '43'
  prometheus:
    repository: cloudfoundry-community/prometheus-boshrelease
    version: 27.0.0
  python-buildpack:
    repository: cloudfoundry/python-buildpack-release
    version: 1.7.31
  pxc:
    repository: cloudfoundry-incubator/pxc-release
    version: 0.41.0
  r-buildpack:
    repository: cloudfoundry/r-buildpack-release
    version: 1.1.13
  routing:
    repository: cloudfoundry/routing-release
    version: 0.229.0
  ruby-buildpack:
    repository: cloudfoundry/ruby-buildpack-release
    version: 1.8.32
  shield:
    repository: starkandwayne/shield-boshrelease
    version: 8.7.4
  shield-addon-bbr:
    repository: shieldproject/shield-addon-bbr-boshrelease
    version: 0.2.1
  silk:
    repository: cloudfoundry/silk-release
    version: 2.43.0
  squid:
    repository: cloudfoundry-community/squid-boshrelease
    version: 1.0.1
  staticfile-buildpack:
    repository: cloudfoundry/staticfile-buildpack-release
    version: 1.5.15
  statsd-injector:
    repository: cloudfoundry/statsd-injector-release
    version: 1.11.18
  syslog:
    repository: cloudfoundry/syslog-release
    version: 11.7.5
  terraform:
    repository: orange-cloudfoundry/terraform-release
    tag_prefix: ''
    version: '4'
  uaa:
    repository: cloudfoundry/uaa-release
    version: 75.15.0
  wireguard:
    repository: orange-cloudfoundry/wireguard-boshrelease
    tag_prefix: ''
    version: '8'
stemcell:
  version: '1.97'
